<?php 
// Start output buffering to catch any unwanted output
ob_start();

// Disable error display to prevent HTML output before JSON
ini_set("display_errors", 0);
ini_set("display_startup_errors", 0);
error_reporting(E_ALL); // Still log errors, just don't display them
ini_set('log_errors', 1);
ini_set('error_log', __DIR__ . '/get_profile_errors.log');

// Set JSON header first
header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=utf-8");

include "conn.php";

// Clear any output that might have been generated by included files
ob_clean();

$date = date("Y-m-d H:i:s");
$current_time = date("H:i:s");

// Helper function to normalize image URLs
function normalizeImageUrl($image_url) {
    if (empty($image_url) || $image_url === 'NA') {
        return $image_url;
    }
    
    // If already a full URL, clean it up and ensure https
    if (preg_match('/^https?:\/\//', $image_url)) {
        // Convert http:// to https:// for security
        $image_url = str_replace('http://', 'https://', $image_url);
        
        // Clean up double slashes (except after https://)
        $image_url = preg_replace('#([^:])//+#', '$1/', $image_url);
        
        return $image_url;
    }
    
    // Construct full URL with https
    $base_url = 'https://' . $_SERVER['HTTP_HOST'];
    
    // If starts with /, use base URL directly
    if (strpos($image_url, '/') === 0) {
        return $base_url . $image_url;
    }
    
    // Otherwise, add webservice path
    $webservice_path = dirname($_SERVER['PHP_SELF']);
    return $base_url . $webservice_path . '/' . ltrim($image_url, '/');
}

/*-------------check method------------------*/
if (!$_GET) {
    $record = ["success" => "false", "msg" => "Please use get method !!!"];
    $data = json_encode($record);
    echo $data;
    return;
}

if (empty($_GET["user_id"])) {
    $record = ["success" => "false", "msg" => "Please send user id!"];
    $data = json_encode($record);
    echo $data;
    return;
}

if (empty($_GET["user_type"])) {
    $record = ["success" => "false", "msg" => "Please send login user type!"];
    $data = json_encode($record);
    echo $data;
    return;
}

$res_bimages = [];
$profile_info = []; // Initialize profile_info to avoid null errors

/*---------------check user id-------------*/
$user_id = $_GET["user_id"];
$active_flag = "yes";
$get_user = $mysqli->prepare(
    "select user_id,user_type,first_name,last_name,user_name,email_id,address,phone,image,postal_code,country,state,city,profession_id,shop_name,latitude,longitude,active_flag from user_master where user_id=? "
);
$get_user->bind_param("i", $user_id);
$get_user->execute();
$get_user->store_result();
$get_user_all = $get_user->num_rows;

if ($get_user_all <= 0) {
    $record = [
        "success" => "false",
        "msg" => "No User Found",
        "status" => "no_user",
    ];
    $data = json_encode($record);
    echo $data;
    return;
} else {
    $get_user->bind_result(
        $user_id,
        $user_type,
        $first_name,
        $last_name,
        $user_name,
        $email_id,
        $address,
        $phone,
        $image1,
        $postal_code,
        $country,
        $state,
        $city,
        $profession_id,
        $shop_name,
        $latitude,
        $longitude,
        $my_active_flag_get
    );
    $get_user->fetch();

    if ($my_active_flag_get == "no") {
        $record = [
            "success" => "false",
            "msg" => "Your account deactivated by admin",
            "status" => "no_user",
        ];
        $data = json_encode($record);
        echo $data;
        return;
    }

    /*-------------------------------------user type buyer-----------------------*/
    if ($user_type == "buyer") {
        $profile_info = [
            "first_name" => $first_name,
            "last_name" => $last_name,
            "user_id" => $user_id,
            "user_name" => $user_name,
            "email_id" => $email_id,
            "user_type" => $user_type,
            "address" => $address,
            "phone" => $phone,
            "image" => $image1,
            "postal_code" => $postal_code,
            "country" => $country,
            "state" => $state,
            "city" => $city,
            "latitude" => $latitude,
            "longitude" => $longitude,
            "all_post" => "NA",
        ];
    }

    /*-------------------------------------user type chef------------------------*/
    if ($user_type == "chef") {
        /*----------------------------------------------get profession name------------------*/
        $get_profession = $mysqli->prepare(
            "select profession_name,image from profession_master where profession_id=?"
        );
        $get_profession->bind_param("s", $profession_id);
        $get_profession->execute();
        $get_profession->store_result();
        $get_profession_name = $get_profession->num_rows;
        if ($get_profession_name > 0) {
            $get_profession->bind_result($profession_name, $pimage);
            $get_profession->fetch();
            if (empty($pimage)) {
                $pimage = "http://www.msnoverseas.com/Images/no-image-available.png";
            }
        } else {
            $profession_name = "NA";
            $pimage = "NA";
        }

        /*------------------------------------get category id and category name-------------------*/
        $get_category = $mysqli->prepare(
            "select cm.category_name,cm.category_id,cm.image from user_category_master ucm inner join category_master cm on ucm.category_id=cm.category_id  where user_id=?"
        );
        $get_category->bind_param("s", $user_id);
        $get_category->execute();
        $get_category->store_result();
        $get_category_name = $get_category->num_rows;
        if ($get_category_name > 0) {
            $get_category->bind_result(
                $category_name,
                $category_id,
                $category_image
            );
            while ($get_category->fetch()) {
                $categoryy[] = [
                    "category_id" => $category_id,
                    "category_name" => $category_name,
                    "category_image" => $category_image,
                ];
            }
        }
        if (empty($categoryy)) {
            $categoryy = "NA";
        }

        $count_followers = $mysqli->prepare(
            "select count(from_user_id) from following_master where to_user_id=?"
        );
        $count_followers->bind_param("i", $user_id);
        $count_followers->execute();
        $count_followers->store_result();
        $count_followers_check = $count_followers->num_rows;
        if ($count_followers_check <= 0) {
            $followers = 0;
        } else {
            $count_followers->bind_result($followers);
            $count_followers->fetch();
        }

        $check_rating = $mysqli->prepare(
            "SELECT avg(rating) as rat FROM `rating_master` WHERE to_user_id='" .
                $user_id .
                "' "
        );
        $check_rating->execute();
        $check_rating->store_result();
        $check_rating->bind_result($rat);
        $check_rating->fetch();

        if (strlen($rat) <= 0) {
            $ratingg = 0;
        } else {
            $rating = $rat;
            $ratingg = round($rating);
        }

        if (!empty($_GET["my_user_id"])) {
            $get_follow = $mysqli->prepare(
                "select following_id from following_master where from_user_id=? and to_user_id=?"
            );
            $get_follow->bind_param("ii", $_GET["my_user_id"], $user_id);
            $get_follow->execute();
            $get_follow->store_result();
            if ($get_follow->num_rows <= 0) {
                $follow_flag = "no";
            } else {
                $follow_flag = "yes";
            }
        } else {
            $follow_flag = "no";
        }

        /*----------------------------------------------get all review data-------------------------------------*/
        $get_review_rating = $mysqli->prepare(
            "SELECT rating_id,to_user_id,from_user_id,order_id,rating,review,inserttime FROM `rating_master` where to_user_id=?"
        );
        $get_review_rating->bind_param("i", $user_id);
        $get_review_rating->execute();
        $get_review_rating->store_result();

        if ($get_review_rating->num_rows <= 0) {
            $all_review_rating = "";
        } else {
            $get_review_rating->bind_result(
                $rating_id,
                $to_user_id,
                $from_user_id,
                $order_id,
                $rating,
                $review,
                $inserttime
            );
            while ($get_review_rating->fetch()) {
                $get_to_user = $mysqli->prepare(
                    "select user_id,first_name,image from user_master where user_id=?"
                );
                $get_to_user->bind_param("i", $from_user_id);
                $get_to_user->execute();
                $get_to_user->store_result();
                $get_to_user->bind_result($fuser_id, $lfirst_name, $rimage);
                $get_to_user->fetch();

                $record[] = [
                    "rating_id" => $rating_id,
                    "my_user_id" => $to_user_id,
                    "rating_user_id" => $fuser_id,
                    "first_name" => $lfirst_name,
                    "image" => $rimage,
                    "order_id" => $order_id,
                    "rating" => $rating,
                    "review" => $review,
                    "inserttime" => $inserttime,
                ];
                $all_review_rating = $record;
            }
            unset($record);
        }

        if (empty($all_review_rating)) {
            $all_review_rating = "NA";
        }

        //----------------------------get all dish by chef id----------------------------------------
        // UPDATED: Query to match post_dish_or_item.php structure
        // Filter by type='chef', order by dish_id DESC (newest first)
        // First try with type filter (since dishes are saved with type='chef')
        
        // Initialize variables first
        $all_dish = [];
        $post_count = 0;
        
        // First try with type filter (dishes are saved with type='chef')
        // Note: 'portion' is a reserved word in MariaDB, so we need backticks
        $get_dish = $mysqli->prepare(
            "SELECT dish_id, user_id, name, meal, service_type, price, description, dish_date, start_time, end_time, `portion`, criteria, category_id 
             FROM dish_master 
             WHERE user_id=? AND type='chef' 
             ORDER BY dish_id DESC"
        );

        // If that fails (type column might not exist), try without type filter
        if (!$get_dish) {
            error_log("get_profile.php: Type column may not exist, trying without type filter. Error: " . $mysqli->error);
            $get_dish = $mysqli->prepare(
                "SELECT dish_id, user_id, name, meal, service_type, price, description, dish_date, start_time, end_time, `portion`, criteria, category_id 
                 FROM dish_master 
                 WHERE user_id=? 
                 ORDER BY dish_id DESC"
            );
        }

        if (!$get_dish) {
            // Still failed, log error but continue with empty dishes
            error_log("get_profile.php: Failed to prepare dish query for user_id: " . $user_id . " Error: " . $mysqli->error);
            $all_dish = "NA";
            $post_count = 0;
        } else {
            $get_dish->bind_param("i", $user_id);
            $get_dish->execute();

            if ($get_dish->error) {
                // Error executing, log and set empty dishes
                error_log("get_profile.php: Error executing dish query for user_id: " . $user_id . " Error: " . $get_dish->error);
                $all_dish = "NA";
                $post_count = 0;
            } else {
                $get_dish->store_result();
                $post_count = $get_dish->num_rows;
                
                error_log("get_profile.php: Found " . $post_count . " dishes in database for chef user_id: " . $user_id);
                
                if ($post_count > 0) {
                    $get_dish->bind_result(
                $dish_id,
                $chef_id,
                $dish_name,
                $meal,
                $service_type,
                $dish_price,
                $dish_description,
                $dish_date,
                $start_time,
                $end_time,
                $portion,
                $criteria,
                $dcategory_id
            );

            while ($get_dish->fetch()) {
                // Log each dish being processed
                error_log("get_profile.php: Processing dish_id: $dish_id, name: $dish_name, user_type param: " . $_GET["user_type"]);
                
                /*-=------------------------get dish images--------------------------------------------*/
                $check_rest_bimages = $mysqli->prepare(
                    "SELECT dish_image_id,image FROM `dish_image_master` where dish_id=? ORDER BY dish_image_id ASC"
                );
                $check_rest_bimages->bind_param("i", $dish_id);
                $check_rest_bimages->execute();
                $check_rest_bimages->store_result();
                
                $res_bimages = [];
                if ($check_rest_bimages->num_rows <= 0) {
                    $res_bimages = "NA";
                } else {
                    $check_rest_bimages->bind_result($dish_image_id, $image);
                    while ($check_rest_bimages->fetch()) {
                        // Normalize image URL to ensure it's a complete, valid URL
                        $normalized_image_url = normalizeImageUrl($image);
                        
                        $res_bimages[] = [
                            "dish_image_id" => $dish_image_id,
                            "kitchen_image" => $normalized_image_url,
                        ];
                    }
                }

                if (empty($res_bimages)) {
                    $res_bimages = "NA";
                }

                $start_time_24 = date("H:i", strtotime($start_time));
                $end_time_24 = date("H:i", strtotime($end_time));

                $current_time = date("H:i:s");
                $current_date = date("Y-m-d");

                // UPDATED: Show all dishes for chef viewing their own profile
                // Only filter by date/time when buyer is viewing
                $viewing_user_type = $_GET["user_type"] ?? "";
                error_log("get_profile.php: Viewing user_type: $viewing_user_type, dish_date: $dish_date");
                
                if ($viewing_user_type == "buyer") {
                    // For buyers, only show dishes that are available now or in future
                    if ($current_date == date("Y-m-d", strtotime($dish_date))) {
                        if (
                            $current_time >= date("H:i:s", strtotime($start_time)) &&
                            $current_time <= date("H:i:s", strtotime($end_time))
                        ) {
                            $all_dish[] = [
                                "dish_id" => $dish_id,
                                "chef_id" => $chef_id,
                                "dish_name" => $dish_name,
                                "meal" => $meal,
                                "service_type" => $service_type,
                                "dish_price" => $dish_price,
                                "dish_description" => $dish_description,
                                "dish_date" => date("d-m-Y", strtotime($dish_date)),
                                "start_time" => date("h:i:a", strtotime($start_time)),
                                "end_time" => date("h:i a", strtotime($end_time)),
                                "start_time_24" => $start_time_24,
                                "end_time_24" => $end_time_24,
                                "criteria" => $criteria,
                                "portion" => $portion,
                                "dish_category_id" => $dcategory_id,
                                "dish_images" => $res_bimages,
                            ];
                        }
                    } elseif ($current_date < date("Y-m-d", strtotime($dish_date))) {
                        $all_dish[] = [
                            "dish_id" => $dish_id,
                            "chef_id" => $chef_id,
                            "dish_name" => $dish_name,
                            "meal" => $meal,
                            "service_type" => $service_type,
                            "dish_price" => $dish_price,
                            "dish_description" => $dish_description,
                            "dish_date" => date("d-m-Y", strtotime($dish_date)),
                            "start_time" => date("h:i:a", strtotime($start_time)),
                            "end_time" => date("h:i a", strtotime($end_time)),
                            "start_time_24" => $start_time_24,
                            "end_time_24" => $end_time_24,
                            "criteria" => $criteria,
                            "portion" => $portion,
                            "dish_category_id" => $dcategory_id,
                            "dish_images" => $res_bimages,
                        ];
                    }
                } else {
                    // For chef viewing their own profile, show ALL dishes (no date/time filter)
                    error_log("get_profile.php: Adding dish to array (chef viewing own profile): dish_id=$dish_id");
                    $all_dish[] = [
                        "dish_id" => $dish_id,
                        "chef_id" => $chef_id,
                        "dish_name" => $dish_name,
                        "meal" => $meal,
                        "service_type" => $service_type,
                        "dish_price" => $dish_price,
                        "dish_description" => $dish_description,
                        "dish_date" => date("d-m-Y", strtotime($dish_date)),
                        "start_time" => date("h:i:a", strtotime($start_time)),
                        "end_time" => date("h:i a", strtotime($end_time)),
                        "start_time_24" => $start_time_24,
                        "end_time_24" => $end_time_24,
                        "criteria" => $criteria,
                        "portion" => $portion,
                        "dish_category_id" => $dcategory_id,
                        "dish_images" => $res_bimages,
                    ];
                }
            } // End of while loop
            
            // Log how many dishes were added to array
            $dish_count_log = is_array($all_dish) ? count($all_dish) : 0;
            error_log("get_profile.php: Added " . $dish_count_log . " dishes to all_dish array for chef user_id: " . $user_id);
        } // End of if ($post_count > 0)
            } // End of else (if no error)
        } // End of if ($get_dish)

        // Log final dish count before setting to NA
        $dish_count_before = is_array($all_dish) ? count($all_dish) : 0;
        error_log("get_profile.php: Final dish count before empty check for chef user_id " . $user_id . ": " . $dish_count_before);
        
        if (empty($all_dish)) {
            $all_dish = "NA";
            error_log("get_profile.php: all_dish was empty, set to NA for chef user_id: " . $user_id);
        } else {
            $dish_count = is_array($all_dish) ? count($all_dish) : 0;
            error_log("get_profile.php: all_dish has " . $dish_count . " dishes for chef user_id: " . $user_id);
        }

        $profile_info = [
            "first_name" => $first_name,
            "last_name" => $last_name,
            "user_id" => $user_id,
            "user_name" => $user_name,
            "email_id" => $email_id,
            "user_type" => $user_type,
            "address" => $address,
            "phone" => $phone,
            "image" => $image1,
            "postal_code" => $postal_code,
            "country" => $country,
            "state" => $state,
            "city" => $city,
            "profession_id" => $profession_id,
            "profession_name" => $profession_name,
            "pimage" => $pimage,
            "category" => $categoryy,
            "latitude" => $latitude,
            "longitude" => $longitude,
            "avg_rating" => $ratingg,
            "followers" => $followers,
            "post_count" => $post_count,
            "all_post" => $all_dish,
            "all_review" => $all_review_rating,
            "follow_flag" => $follow_flag,
        ];
    }

    /*----------------------------------user type grocer--------------------*/
    if ($user_type == "grocer") {
        $count_followers = $mysqli->prepare(
            "select count(from_user_id) from following_master where to_user_id=?"
        );
        $count_followers->bind_param("i", $user_id);
        $count_followers->execute();
        $count_followers->store_result();
        $count_followers_check = $count_followers->num_rows;
        if ($count_followers_check <= 0) {
            $followers = 0;
        } else {
            $count_followers->bind_result($followers);
            $count_followers->fetch();
        }

        $check_rating = $mysqli->prepare(
            "SELECT avg(rating) as rat FROM `rating_master` WHERE to_user_id='" .
                $user_id .
                "' "
        );
        $check_rating->execute();
        $check_rating->store_result();
        $check_rating->bind_result($rat);
        $check_rating->fetch();

        if (strlen($rat) <= 0) {
            $ratingg = 0;
        } else {
            $rating = $rat;
            $ratingg = round($rating);
        }

        if (!empty($_GET["my_user_id"])) {
            $get_follow = $mysqli->prepare(
                "select following_id from following_master where from_user_id=? and to_user_id=?"
            );
            $get_follow->bind_param("ii", $_GET["my_user_id"], $user_id);
            $get_follow->execute();
            $get_follow->store_result();
            if ($get_follow->num_rows <= 0) {
                $follow_flag = "no";
            } else {
                $follow_flag = "yes";
            }
        } else {
            $follow_flag = "no";
        }

        /*----------------------------------------------get all review data-------------------------------------*/
        $get_review_rating = $mysqli->prepare(
            "SELECT rating_id,to_user_id,from_user_id,order_id,rating,review,inserttime FROM `rating_master` where to_user_id=?"
        );
        $get_review_rating->bind_param("i", $user_id);
        $get_review_rating->execute();
        $get_review_rating->store_result();

        if ($get_review_rating->num_rows <= 0) {
            $all_review_rating = "";
        } else {
            $get_review_rating->bind_result(
                $rating_id,
                $to_user_id,
                $from_user_id,
                $order_id,
                $rating,
                $review,
                $inserttime
            );

            while ($get_review_rating->fetch()) {
                $get_to_user = $mysqli->prepare(
                    "select user_id,first_name,image from user_master where user_id=?"
                );
                $get_to_user->bind_param("i", $from_user_id);
                $get_to_user->execute();
                $get_to_user->store_result();
                $get_to_user->bind_result($fuser_id, $first_name, $rimage);
                $get_to_user->fetch();

                $record[] = [
                    "rating_id" => $rating_id,
                    "my_user_id" => $to_user_id,
                    "rating_user_id" => $fuser_id,
                    "first_name" => $first_name,
                    "image" => $rimage,
                    "order_id" => $order_id,
                    "rating" => $rating,
                    "review" => $review,
                    "inserttime" => $inserttime,
                ];
                $all_review_rating = $record;
            }
            unset($record);
        }

        if (empty($all_review_rating)) {
            $all_review_rating = "NA";
        }

        //----------------------------get all dish by grocer id----------------------------------------
        // UPDATED: Query to match post_dish_or_item.php structure
        // Filter by type='grocer', order by dish_id DESC (newest first)
        // Try to query with type filter first, if it fails, try without type filter (for backward compatibility)
        $get_dish = $mysqli->prepare(
            "SELECT dish_id, user_id, name, service_type, price, description 
             FROM dish_master 
             WHERE user_id=? AND type='grocer' 
             ORDER BY dish_id DESC"
        );

        if (!$get_dish) {
            // If type column doesn't exist, try without type filter
            $get_dish = $mysqli->prepare(
                "SELECT dish_id, user_id, name, service_type, price, description 
                 FROM dish_master 
                 WHERE user_id=? 
                 ORDER BY dish_id DESC"
            );
        }

        // Initialize variables
        $all_dish = [];
        $post_count = 0;

        if ($get_dish) {
            $get_dish->bind_param("i", $user_id);
            $get_dish->execute();

            if (!$get_dish->error) {
                $get_dish->store_result();
                $post_count = $get_dish->num_rows;
            }
        }

        if ($post_count > 0) {
            $get_dish->bind_result(
                $dish_id,
                $grocer_id,
                $dish_name,
                $service_type,
                $dish_price,
                $dish_description
            );

            while ($get_dish->fetch()) {
                /*-=------------------------get dish images--------------------------------------------*/
                $check_rest_bimages = $mysqli->prepare(
                    "SELECT dish_image_id,image FROM `dish_image_master` where dish_id=? ORDER BY dish_image_id ASC"
                );
                $check_rest_bimages->bind_param("i", $dish_id);
                $check_rest_bimages->execute();
                $check_rest_bimages->store_result();

                $res_bimages = [];
                if ($check_rest_bimages->num_rows <= 0) {
                    $res_bimages = "NA";
                } else {
                    $check_rest_bimages->bind_result($dish_image_id, $image);
                    while ($check_rest_bimages->fetch()) {
                        // Normalize image URL to ensure it's a complete, valid URL
                        $normalized_image_url = normalizeImageUrl($image);
                        
                        $res_bimages[] = [
                            "dish_image_id" => $dish_image_id,
                            "kitchen_image" => $normalized_image_url,
                        ];
                    }
                }

                if (empty($res_bimages)) {
                    $res_bimages = "NA";
                }

                $all_dish[] = [
                    "dish_id" => $dish_id,
                    "grocer_id" => $grocer_id,
                    "dish_name" => $dish_name,
                    "service_type" => $service_type,
                    "dish_price" => $dish_price,
                    "dish_description" => $dish_description,
                    "dish_images" => $res_bimages,
                ];
            }
        }

        if (empty($all_dish)) {
            $all_dish = "NA";
        }

        $profile_info = [
            "first_name" => $first_name,
            "last_name" => $last_name,
            "user_id" => $user_id,
            "user_name" => $user_name,
            "email_id" => $email_id,
            "user_type" => $user_type,
            "address" => $address,
            "phone" => $phone,
            "image" => $image1,
            "postal_code" => $postal_code,
            "country" => $country,
            "state" => $state,
            "city" => $city,
            "shop_name" => $shop_name,
            "latitude" => $latitude,
            "longitude" => $longitude,
            "avg_rating" => $ratingg,
            "followers" => $followers,
            "post_count" => $post_count,
            "all_post" => $all_dish,
            "all_review" => $all_review_rating,
            "follow_flag" => $follow_flag,
        ];
    }
}

// Ensure profile_info is always set, even if empty
if (empty($profile_info)) {
    // If profile_info is not set, create a minimal response with user data
    if (isset($user_id) && isset($user_type)) {
        $profile_info = [
            "user_id" => $user_id,
            "user_type" => $user_type,
            "first_name" => isset($first_name) ? $first_name : "",
            "last_name" => isset($last_name) ? $last_name : "",
            "all_post" => "NA",
        ];
    } else {
        $record = ["success" => "false", "msg" => "No Data Found"];
        $data = json_encode($record);
        echo $data;
        return;
    }
}

$record = [
    "success" => "true",
    "msg" => "data found",
    "profile_data" => $profile_info,
];

// Log response for debugging
error_log("get_profile.php: Returning profile_data with all_post count: " . (isset($profile_info['all_post']) && is_array($profile_info['all_post']) ? count($profile_info['all_post']) : (is_string($profile_info['all_post']) ? $profile_info['all_post'] : 'unknown')));

// Update user insert_time before sending response (silently, don't let errors break JSON)
$update = $mysqli->prepare(
    "Update `user_master` set `insert_time`=? Where `user_id`=?"
);
if ($update) {
    $update->bind_param("si", $date, $_GET["user_id"]);
    @$update->execute(); // Suppress any errors
    $update->close();
}

// Ensure clean JSON output - no HTML before this
// Clean any buffered output and send only JSON
ob_end_clean();
$data = json_encode($record, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
echo $data;
exit; // Use exit instead of return to prevent any trailing output

?>

